apiVersion: v2
name: ack-parent-chart
description: A Helm chart containing all ACK charts as sub-charts 
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: eks-chart
  alias: eks
  version: v0.1.8
  repository: "oci://public.ecr.aws/aws-controllers-k8s"
  condition: eks.enabled
- name: iam-chart
  alias: iam
  version: v0.1.1
  repository: "oci://public.ecr.aws/aws-controllers-k8s"
  condition: iam.enabled
- name: ec2-chart
  alias: ec2
  version: v0.1.0
  repository: "oci://public.ecr.aws/aws-controllers-k8s"
  condition: ec2.enabled